### ISSUE TITLE
Save Pivot Table 

### ISSUE THREAD

**Issue by meetdileep** [deecay/redmine_pivot_table#11]
Hi Deecay,

Hope you are doing fine. First of all thanks for developing such a nice plugin which is very useful in redmine.

I had a query if one pivot table is created, do we have any option saving it as template, it mean when ever we open the pivot , it should display last saved.

Thanks in advance,

Dileep

**Comment by deecay** [comment]
Hi,

Saving feature is a future goal. 

Meanwhile, if you've got the pivot table you would like to save, click "Show URL" at the bottom of the pivot table, and use the shown URL as browser favorites or wiki page links.

**Comment by deecay** [comment]
Please try the latest release.

**Comment by meetdileep** [comment]
Hi,

Thank you so much the development. There is one issue which I am facing while installing the plugin with latest release of 0.4 Version. I have done git clone to my redmine server and when I run the migrate, redmine application is not running and even I am searching in Production Log, no information is being created. Kindly help me in resolving this issue.

Thanks in Advance,

Dileep

**Comment by deecay** [comment]
As mentioned in the readme, no migration is required. 
If you don't see anything in Production Log, see web server logs like apache logs/error_log and see if there is any information.
