### ISSUE TITLE
Redmine Queries 

### ISSUE THREAD

**Issue by ste26054** [deecay/redmine_pivot_table#14]
Hi,

Thank you for this plugin, it's very powerful !

Are there any plans to adapt it to issue queries ? 

For instance, we could pre filter a certain list of issues with the filtering / querying abilities of redmine, then build the pivot table based on this list ?

Many thanks

**Comment by deecay** [comment]
Hi,

Thanks your your comment.

The answer to your question is "it's already there." For the proper user interface is missing, it is very confusing, but the functionality is there.

Go to issues tab and filter out the issues as you may wish. Then click the Pivot tab. You should realize that the total number of issues are the filtered issue count.

The missing user interface is the "Filter" section for pivottable view, just like Gannt view. Gantt view properly shows the inherited filter from the Issue page. I am planning the enhancement in the next release.

**Comment by ste26054** [comment]
Oh ok ! I didn't notice that, thanks for your answer !
