### ISSUE TITLE
Issues are taken from current query

### ISSUE THREAD

**Issue by AThomsen** [deecay/redmine_pivot_table#15]
The list of issues is taken from the current query (`retrieve_query` in the controller). 

This means that any filters that are applied in the "Issues" view is also applied to the "Pivot" view. This is confusing as there's no way to edit the filters from the Pivot view. Also, it is counterintuitive that these two views "cross talks".

A fix could be to copy the code from `retrieve_query` where the new default query for the current project is created.

**Comment by deecay** [comment]
Hi,

Thanks for the idea.
I would like to comply to the "Issue Filter in Session" idea, and would try to add Filter section on top of pivottable UI so the filters are editable. (see #14) 

I believe this way is better than cutting off the pivottable UI from Redmine's filter UI, which we are accostomed to.

**Comment by AThomsen** [comment]
Sounds good. Just wanted to be sure you was aware of this "feature" :-)

**Comment by deecay** [comment]
Feature added in  12f63d74ced8a41f691a1e6d0c37497e2082b461
