### ISSUE TITLE
Show url does not add the result of the field

### ISSUE THREAD

**Issue by aceccarelli** [deecay/redmine_pivot_table#16]
Hi,

I created a table as attachment but the link created by "Show URL" does not include the "Result Score".
This field is a custom field.

![pivot](https://cloud.githubusercontent.com/assets/2286593/13955103/320da1fc-f022-11e5-883a-cf11a901450d.PNG)

Thanks!

**Comment by deecay** [comment]
Please try 3c2e68ef1a9ad03ec311d596661e140d3897e502

**Comment by aceccarelli** [comment]
Hi,
Perfect!
It works.

Thanks!
