### ISSUE TITLE
please update your readme.md file

### ISSUE THREAD

**Issue by archonwang** [deecay/redmine_pivot_table#18]
I tested and used it on Redmine 3.2.X and it worked well, Great!!
Thanks.

**Comment by deecay** [comment]
Hi, thanks for the comment.

Which part of the readme do you suggest to update?
If you are talking about Redmine version, I intended to avoid writing out all supported versions by saying:
"(supports) following versions **or above**: •Redmine version 2.6.0.stable"

**Comment by archonwang** [comment]
Thanks for you reply.  I think it should be enough in ReadmeFile.
