### ISSUE TITLE
pivot_table use custom value can not be loaded the first value

### ISSUE THREAD

**Issue by archonwang** [deecay/redmine_pivot_table#19]
it's stange, when I use the custom field , it can not load the first value and display null for the count.

**Comment by deecay** [comment]
Hi. Could you give me more details? What data type of c.f. is it? Text? Boolean?
What do you mean by "first"? First c.f. of a ticket, or the first value of the n numbers of tickets?

I would need mode specific details of the issue to look into it.

**Comment by archonwang** [comment]
I used customize field name like 'Environment' ,  type as list,
values as 
'
中文环境
English
Korean
US English
'

and when I use the field in pivot_table ,it can not load value "中文环境"，and it is the first value I have defined.

**Comment by deecay** [comment]
Looks like working in my test environment. Does the place of the entry (first value) matter? Does changing the 4 characters to a different one matter?

![snapcrab_noname_2016-5-13_14-51-45_no-00](https://cloud.githubusercontent.com/assets/1698635/15239078/60e9f504-191a-11e6-9390-7c26fc174501.jpg)

**Comment by archonwang** [comment]
Sorry that I do not know how to submit images on github.

YES.  
 just as you see, the first value lost,  but it still can be counted in table.

**Comment by deecay** [comment]
Are you talking about the "4" with Null header in my image? The header is null because 4 tickets have no environment value assigned. If you select all 4 tickets and assign environments, then the null row will disappear.

I'm not sure if I'm getting your question right, so please tell me otherwise.

**Comment by archonwang** [comment]
I See,  Thanks for your apply.
