### ISSUE TITLE
Please add support for Redmine 2.3.1.stable.11898

### ISSUE THREAD

**Issue by wreiske** [deecay/redmine_pivot_table#2]
Hello!

It would be greatly appreciated if you could support older Redmine versions.

Redmine 2.3.1.stable.11898 Specifically.

Thanks,
Will

**Comment by deecay** [comment]
Hi,

Do you encounter an error?
What version of IE are you using?

**Comment by deecay** [comment]
Should work now.

**Comment by wreiske** [comment]
Still looks broken... No server error this time.

<img width="898" alt="screen shot 2015-08-24 at 6 25 07 am" src="https://cloud.githubusercontent.com/assets/6295044/9438040/ed860d2a-4a28-11e5-8e8d-2206ef3cc386.png">

**Comment by wreiske** [comment]
I've fixed this in a pull request, https://github.com/deecay/redmine_pivot_table/pull/5

**Comment by deecay** [comment]
Thanks. Merged.
