### ISSUE TITLE
Want to see zero value in line chart

### ISSUE THREAD

**Issue by pockmonst** [deecay/redmine_pivot_table#22]
Hi.
I want to use your plugin to check how many issues in some category with Line chart.
But zero value in line chart is not displayed, like this image. The blue line middle point is snaped.(value zero)
![image](https://cloud.githubusercontent.com/assets/20177477/16401645/3e8f6202-3d21-11e6-8c56-4faaab411610.png)

And Vertical value(Count())'s min value isn't zero. I want to see Vertical value's min is zero and connected line.

Is there some advice to can I do it?

**Comment by deecay** [comment]
Hello,

That will require patching c3 javascript, for it doesn't have options to control your requested feature.

Changing row 136 of c3_renderers.js from
`row.push(null);`
to
`row.push(0);`
will probably achieve what you request.

Redmine pivot table does not have any interface to pass options to C3, so even this was an available setting in C3, there is no way to set it through this plugin. So patching might be the realistic solution if you insist on this graph format.

Hope this helps.

**Comment by pockmonst** [comment]
Oh, Thanks GOD. You saved me!:)
It works perfectly what I want!!!

Thanks for your help and your great plugin!^^
