### ISSUE TITLE
Hide unused field

### ISSUE THREAD

**Issue by pockmonst** [deecay/redmine_pivot_table#23]
Hello.
I have 62 fields to used in pivot table plugin.
but I use just 2 field, so the rest things are showed like this image.
![default](https://cloud.githubusercontent.com/assets/20177477/16865400/6dd984f8-4a9f-11e6-91be-64612d420cfb.PNG)

It looks very crowded so I want hide them or move under the page.
If you use this(https://github.com/nicolaskruchten/pivottable) source, author said lastest version provide switch list function(https://github.com/nicolaskruchten/pivottable/issues/181)
Is it possible to apply on your plugin?

**Comment by deecay** [comment]
Hi,

Actually I have forced to list them horizontal as a design decision.

If you want to see a different behavior, patch  app / views / pivottables / index.html.erb , line 147

`unusedAttrsVertical: false`
to
`unusedAttrsVertical: true`

I might make this a configurable parameter if enough people agree to do so.

**Comment by pockmonst** [comment]
Thanks! It works very well!
I think almost people didn't make many custom fields likes me...:)
