### ISSUE TITLE
Pivot for all projects

### ISSUE THREAD

**Issue by Niremizov** [deecay/redmine_pivot_table#27]
Is it possible to view pivot for all projects, without creating main parent project?

**Comment by deecay** [comment]
You can't for now. 

The redmine-instance-wide pivottable will not have access control / authorization nor query saving, for these depend on a project. I may implement the feature if that's okay.

**Comment by archonwang** [comment]
+1

**Comment by Niremizov** [comment]
> The redmine-instance-wide pivottable will not have access control / authorization nor query saving, for these depend on a project. 

@deecay On this page **/issues** I can access all projects wide quiries, can pivottable quiries do the same?

PS: I'm not really good at Redime plugins development, so my I do not understand all details.

**Comment by deecay** [comment]
No, you are right. I was not careful enough in my description. There are two types of queries, project dependent and non dependent. So all project pivottable should be able to access all project queries.

**Comment by Niremizov** [comment]
@deecay ok, so can I hope this cool feature would be implemented some day? Thx in advance!

**Comment by deecay** [comment]
Implemented now.
@88597887d5d741635cee50e28bead3606bea9a0a

**Comment by frankz96** [comment]
> Implemented now. @88597887d5d741635cee50e28bead3606bea9a0a

Hi, how to use this? I still can not view pivot for all projects.
