### ISSUE TITLE
Why there are no table show for issue? but it is ok for activity.

### ISSUE THREAD

**Issue by 45592858** [deecay/redmine_pivot_table#36]
Why there are no table show for issue? but it is ok for activity.
![image](https://cloud.githubusercontent.com/assets/17882261/22003723/d68ef7de-dc90-11e6-80a7-64f3d7411c31.png)

![image](https://cloud.githubusercontent.com/assets/17882261/22003753/2600d5f8-dc91-11e6-99a8-66b69f9d5658.png)

**Comment by deecay** [comment]
Hi,

Can you send or post a logfile when you try to display issues?

**Comment by 45592858** [comment]
Sorry, it may cause as my Redmine version is 2.5.2.stable. It is not support this version, right?

**Comment by deecay** [comment]
No, I haven't tested it yet with 2.5.x. So the version might be the issue. I can't say.
Feel free to send me an error log.
