### ISSUE TITLE
Add support to Redmine 3.1.x

### ISSUE THREAD

**Issue by topkool** [deecay/redmine_pivot_table#4]
Superb plugin and it would be very great if you can add the compatibility with Redmine 3.x and higher

**Comment by deecay** [comment]
I suspect it is. Did you encounter any error?
One person said it worked for 3.0.3. https://www.redmine.org/plugins/redmine_pivot_table

**Comment by topkool** [comment]
I was able to install it, but the tab "Pivot" is empty (see attachment).

![image1](https://cloud.githubusercontent.com/assets/5410883/9332817/d0f5657c-45c6-11e5-8102-2931a0217b13.png)

**Comment by deecay** [comment]
I see. Your Redmine and browser version?

**Comment by topkool** [comment]
Here thery are:
- Redmine: 3.1.0
- Browser: Chrome 46.0.2478.0 dev-m (64-bit)

**Comment by deecay** [comment]
I have setup clean 3.1.0 stable with bitnami redmine, and the plugin worked fine.
It seems to be some modification or the installed plugin is causing your problem.

**Comment by topkool** [comment]
I uninstalled all the plugins one by one, and the issue is still there :-(

However, I tried to enable the plugin on another project (same Redmine, same database, same plugins), and it works.

So the issue sems to be related to that particular project.

**Comment by deecay** [comment]
Alright. Let me close this then. Let me know if you find out any possible cause.

**Comment by topkool** [comment]
I continued the investigation and the tests...

I took one of my project on which the plugin seems to work. I used it without any problem. However, once I check "Issue closed", the bug comes back (no pivot table displayed).

When the "issue closed" is disabled, there are 34 issues (Pivot table displayed)
When the "issue closed" is enabled, there are 106 issues. (No pivot table displayed)

When I go back to the first project, I have the following volume of data:
- Open issue only = 147 tickets (No pivot table displayed)
- Open + closed issues = 218 tickets. (No pivot table displayed)

Do you think the number of tickets might be the root cause of the problem?

**Comment by deecay** [comment]
I have created 200+ dummy tickets in Redmine 3.1.1, with some closed and some open status, and found no issue.

My guess now is that there are some unhandled cases in your 106 - 34 = 72 issues. Maybe one of them has special characters in the Notes, etc. If you can re-open the 106 closed issues in some bulk size at a time, maybe you can track down whether it is a issue specific problem or not.

Press F12 when you encounter error, to see if there is a javascript error.

**Comment by topkool** [comment]
When I checked the "Issue closed" option, I got a Javascript error "Uncaught SyntaxError: Unexpected token " on the following line:

~~~
data = [ {
        "ID": '<ahref=\"/issues/40\">40<\/a>',
        "Project": '<ahref=\"/projects/xxx\">xxx<\/a>',
        "Tracker": 'Bug',
...
            } ];
...
~~~

Chrome displays an error on the simple quotes (shouldn't it be double-quotes?).

**Comment by topkool** [comment]
I figured out the issue.

First, double quotes should be used instead of single quotes, but the root issue is not there.
However, some fields are empties

~~~
data = [ {
        "parameter": ,
...
            } ];
~~~

**Comment by topkool** [comment]
The commit #5 fixed that issue.
