### ISSUE TITLE
Save output to PDF, PNG or SVG

### ISSUE THREAD

**Issue by gnovelli** [deecay/redmine_pivot_table#40]
We are using Pivot plugin and it has been really appreciated.
I have been asked about the possibility to print the output of the plugin.
Checking about its behaviour I see that output content is inside:
<td valign="top" class="pvtRendererArea" style="opacity: 1;">
Is it possible to add a feature for saving its content?

Regards,
Giovanni

**Comment by deecay** [comment]
Hi!

Could you tell me what the use cases are? Are PrimoPDF and/or PrintScreen built-in to OS not good enough?

**Comment by gnovelli** [comment]
Hello,
the use case is this: management would like to use such pivot tables and graphs. It's possible to save the query which define the resulting pivot. They would like to make it possible saving output to in order to use it outside redmine. The use case is very general. Management doesn't have time and capabilities in order to use tricks for saving/printing as it's possible of course. I don't know PrimoPDF. PrintScreen as I know is a capability built in the OS but requires that you cut the resulting output every time you produce and capture it. I was thinking about the possibility to have the rendered output translable to a persistent file as, perhaps, knowing well the underlying javascript libraries should be possible for who is proficient with them. That's all.

**Comment by deecay** [comment]
If some non-manager is going to click some "download" link in Redmine, he might as well save the whole page with PrimoPDF, CutePDF, Print Friendly & PDF, or other html-to-PDF converter. 

I have looked briefly into rasterizeHTML.js, dom-to-image, html2canvas, domvas, etc, but I couldn't find any cross-browser, light weight solution that I might be able to integrate.

You'll have to wait until something changes.
