### ISSUE TITLE
Could you please add support for redmine 4.0.x?

### ISSUE THREAD

**Issue by NicolaTramarin** [deecay/redmine_pivot_table#56]
Installing the plugin on Redmine 4.0.2, the services start and after short time stop. No info in log.

Thank you very much!

**Comment by deecay** [comment]
Hi.

I do not have 4.0 environment now. Will you be able to test the code if I made a feature branch?

**Comment by deecay** [comment]
Now it should be okay with Redmine 4.x.
Closing.

**Comment by NicolaTramarin** [comment]
It works well, thank you very much!
