### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by FumbleBe** [deecay/redmine_pivot_table#6]
On a redmine 3.1.1.
I installed the plugin, enabled it to a project, but when I go to "Pivot", I got an "Internal error" page:

"Internal error

An error occurred on the page you were trying to access.
If you continue to experience problems please contact your Redmine administrator for assistance.

If you are the Redmine administrator, check your log files for details about the error."

In the logs, I got:

Rendered plugins/redmine_pivot_table/app/views/pivottables/index.html
Completed 500 Internal Server Error in 160ms (ActiveRecord: 4.6ms)

ActionView::Template::Error (undefined method `caption' for nil:NilClas
    107:               <%= raw %|rendererName: "#{@rendererName}",| if
    108:               <%= raw %|aggregatorName: "#{@aggregatorName}",|
    109:               <%= raw %|vals: ["#{@vals.join('","')}"],| if @v
    110:               <%= raw @rows == nil ? %|rows: ["#{pv_caption(:f
    111:               <%= raw @cols == nil ? %|cols: ["#{pv_caption(:s
    112:               unusedAttrsVertical: false
    113:            }, false, "<%= @language %>");
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

Any help will be appreciate 

regards,

**Comment by deecay** [comment]
Try https://github.com/deecay/redmine_pivot_table/tree/issue/nil_column and let me know how it goes.

**Comment by thienngho** [comment]
it's okay, pls MR this
