### ISSUE TITLE
Display of tasks in the fields contains the URL

### ISSUE THREAD

**Issue by koren85** [deecay/redmine_pivot_table#62]
Greetings
First of all, I want to say thank you for the wonderful plugin!
I have an urgent problem with the display of tasks. Together with the task ID, a link to the task (URL) is displayed. It is very inconvenient to see information superfluous for the user.

![image](https://user-images.githubusercontent.com/27845271/55869534-5a99f180-5b8f-11e9-89b4-05e42ab17103.png)

What am I trying to get using this plugin:
1) I need to see the loading of staff for each day during a certain time range.
For each day in the time range, I need to see the scheduled time for the task and actually spent time on the task.
Vertically I choose for this
"Assigned to"
Horizontally I choose "Start date" and "Estimate of time costs".

Questions:
How to remove the URL and leave only the task ID?

How can I get a grid where each column will be every day from the selected time range?

Am I using the plugin correctly? Maybe there is a better way to get the information I need?

**Comment by deecay** [comment]
Hi,

1. What does you aggregator look like? "List Unique Values / ID"?

2. This is a major and known limitation of any pivot table. When there are no data for that day, that day will not appear as a column. Pivot is not a table nor time series, it's a way to aggregate existing data.

**Comment by koren85** [comment]
Hello!
1) 

> "List Unique Values / ID?"
 - Yes
pivot table = Table
aggregator =  List Unique Values 
aggregate field = ID

2)
Yes, I understand the essence of the aggregated table.
This question does not apply to the work of the plugin. The question is rather about the functionality of the Redmine.

Thanks for the quick response!

**Comment by deecay** [comment]
For 1, I will update the plugin soon to support your case.

For 2, I have no idea.

**Comment by koren85** [comment]
thank you very much in advance! I look forward to solving this problem.
As for the second question, i will let you know if i find a solution.
