### ISSUE TITLE
Compatibility with extra_queries plugin

### ISSUE THREAD

**Issue by koren85** [deecay/redmine_pivot_table#64]
Hello!
Thanks again for the plugin!
When used in conjunction with the extra_queries plugin, it becomes impossible to go to the saved pivot table query.
Without the "extra_queries" plugin installed, when opening a saved query, the pivot table URL looks like "projects / ef8f5f95-66dc-476b-a37f-77e2ea5ed7be / pivottables? Query_id = 776"
With the plugin installed, the URL looks like "extra_queries / query_group / queries / ef8f5f95-66dc-476b-a37f-77e2ea5ed7be? Type = pivottables"
Is it possible to somehow work together plug-ins?
Thank you in advance!

**Comment by deecay** [comment]
Hi,

Unfortunately, I cannot help with compatibility issues.
