### ISSUE TITLE
its working in redmine 4.0.4 ???

### ISSUE THREAD

**Issue by ashrafalzyoud** [deecay/redmine_pivot_table#66]
can u help me about this 
not any data shown in pivottable if I have my oldDB
but if I have newDB the pivottable working in redmine 4.0.4
I think need migrate

**Comment by deecay** [comment]
Hi, error message please?

**Comment by ashrafalzyoud** [comment]
![aaaa](https://user-images.githubusercontent.com/50211455/61334077-abc21d00-a831-11e9-9776-14138c187ee9.png)

**Comment by ashrafalzyoud** [comment]
Current user: admin (id=1)
  Rendering plugins/redmine_pivot_table/app/views/pivottables/index.html.erb within layouts/base
  Rendered queries/_filters.html.erb (15.7ms)
  Rendered issues/_sidebar.html.erb (4.2ms)
  Rendered plugins/redmine_pivot_table/app/views/pivottables/index.html.erb within layouts/base (5486.1ms)
Completed 200 OK in 5604ms (Views: 4976.0ms | ActiveRecord: 575.4ms)
Started GET "/projects/sale2/pivottables?utf8=%E2%9C%93&set_filter=1&pivot=1&f%5B%5D=status_id&op%5Bstatus_id%5D=o&f%5B%5D=&table=&rows=&cols=&rendererName=&aggregatorName=&attrdropdown=" for 172.17.100.1 at 2019-07-17 01:20:51 +0300
Processing by PivottablesController#index as HTML
  Parameters: {"utf8"=>"✓", "set_filter"=>"1", "pivot"=>"1", "f"=>["status_id", ""], "op"=>{"status_id"=>"o"}, "table"=>"", "rows"=>"", "cols"=>"", "rendererName"=>"", "aggregatorName"=>"", "attrdropdown"=>"", "project_id"=>"sale2"}
  Current user: admin (id=1)
  Rendering plugins/redmine_pivot_table/app/views/pivottables/index.html.erb within layouts/base
  Rendered queries/_filters.html.erb (29.8ms)
  Rendered issues/_sidebar.html.erb (2.9ms)
  Rendered plugins/redmine_pivot_table/app/views/pivottables/index.html.erb within layouts/base (5413.0ms)
Completed 200 OK in 5506ms (Views: 4852.0ms | ActiveRecord: 600.3ms)
Started GET "/projects/sale2/pivottables" for 172.17.100.1 at 2019-07-17 01:21:51 +0300
Processing by PivottablesController#index as HTML
  Parameters: {"project_id"=>"sale2"}
  Current user: admin (id=1)

**Comment by ashrafalzyoud** [comment]
what i can do to this plugin work with my DB , i think the problem form another plugins but im unstall all it, but the problem still not work

**Comment by deecay** [comment]
Looks like a javascript error. Can you show me the Browser's developer console?

**Comment by ashrafalzyoud** [comment]
how i can show it to u ???Browser's developer console?
all internet browser( IE AND CHORME and firefox) not working

**Comment by deecay** [comment]
Press F12 in Chrome.

**Comment by ashrafalzyoud** [comment]
sorters: function(attr) {
                  if(attr === "Status") {
                      return sortAs(["New", "Obsolete", "In Progress", "Resolved", "Feedback", "Closed", "Completed", "Rejected", "Approved", "قيد الدراسة"]);
                  }
		  else if(attr === "Tracker") {
		      **### return sortAs(["Operational goal", "Task", "Action", "الهدف", "KPI "E"", " الهدف الإستراتيجي", "الهدف التشغيلي", "مهمة", "الأداء", "أسم العطاء", "احالة متعددة", "مؤشرات الاداء", "أجهزة الانذار", "الحماية الامنية", "المرافقات الامنية", "التأجير", "شركات الاتصالات", "متفرقة", "احصائيات العقود والاتفاقيات"]);**
		  }
              },
              onRefresh: update_url,

              rendererName: "",
              aggregatorName: "",
              vals: [""],
                rows: [""],
                cols: [""],
              unusedAttrsVertical: false
           }, false, "en");

　　$("#output").click(function(e){
        if (e.target.href ) {
            window.open(e.target,'_blank');
　　　　　　return false;
　　　　};
    });
});

**Comment by ashrafalzyoud** [comment]
your plugin support arabic language??? if tracker in arabic

**Comment by deecay** [comment]
Interesting to see Arabic  :smile: 

Is it possible to rename the column `KPI "E"` to something else that does not involve double quotation? This part seems to be the cause of javascript error.

**Comment by ashrafalzyoud** [comment]
thx for u very much its working now

**Comment by ashrafalzyoud** [comment]
the custom field must be in ( integer or float to collect )
